### ISSUE TITLE
Support for Zip64 Extensions

### ISSUE THREAD

**Issue by benrudolph** [holm/openpyxl#1]
Currently working with `openpyxl`. Been going great so far, but unfortunately there's no way to enable Zip64 extensions when building archives. Does it makes sense to add this functionality? This allows you to write zip files larger than 4GB: https://docs.python.org/2/library/zipfile.html

**Comment by holm** [comment]
This is just my fork from bitbucket to add some bug fixes. You should add your request here: https://bitbucket.org/openpyxl/openpyxl
